/// Flutter icons PokeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class PokeIcons {
  PokeIcons._();

  static const _kFontFam = 'PokeIcons';
  static const String? _kFontPkg = null;

  static const IconData filter =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData generation =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
